name: buslink
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  # FIX 1: Corrected the backtick to a single quote
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0
  flutter_dotenv: ^6.0.0

  provider: ^6.0.0
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/google.jpeg
    - .env