name: buslink
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  # FIX 1: Corrected the backtick to a single quote
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0
  flutter_dotenv: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

  provider: ^6.0.0
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  url_launcher: ^6.3.1
  flutter_stripe: ^12.1.1
  flutter_stripe_web: ^7.1.1
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.2
  http: ^1.6.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - .env
